website/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

website/dresses/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'dresses'

urlpatterns = [
    # /dresses/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/dresses/register
    url(r'^register/$',views.UserFormView.as_view(), name='register'),

    # /dresses/4242/
    url('^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail2'),

    #/dresses/lehengas/add/
    url(r'lehengas/add/$',views.LehengasCreate.as_view(), name='lehenga-add'),

    #dresses/lehengas/2/
    url(r'lehengas/(?P<pk>[0-9]+)/$',views.LehengasUpdate.as_view(), name='lehenga-update'),

    #dresses/lehengas/2/delete
    url(r'lehengas/(?P<pk>[0-9]+)/delete/$',views.LehengasDelete.as_view(), name='lehenga-delete'),

    url(r'login/$', views.login , name='login'),

    url(r'logout/$', views.logout , name='logout'),

    url(r'auth/$', views.auth_view , name='authentiate'),

    url(r'description/$', views.DescView.as_view(), name='description'),

    path('search/',views.search_list,name='search'),

    url(r'^list/$', views.product_list ,name='list')



]

website/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    #orders/create/
    url(r'^create/$', views.order_create, name='order_create'),

    url(r'^create/completed/$', views.completed ,name="completion_msg"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('dresses/', include('dresses.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/cart/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

website/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

website/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from dresses.models import Lehengas,weddingLehenga
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Lehengas, id=product_id)
    cart.add(product, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Lehengas, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

website/cart/templates/cart/detail.html
{% extends 'dresses/base.html' %}
{% load staticfiles %}

{% block body %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with total_items=cart|length %}
                    {% if cart|length >= 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }},Rs. {{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>

            <table class="table table-striped table-hover">
                <thead style="background-color: black">

                    <tr>
                        <th><font color="white" >Image</font></th>
                        <th><font color="white" >Product</font></th>
                        <th><font color="white" >Quantity</font></th>
                        <th><font color="white" >Remove</font></th>
                        <th><font color="white" >Unit Price</font></th>
                        <th><font color="white" >Price</font></th>
                    </tr>

                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{{ product.lehenga_pic }}" alt="..." style="height: 100px; width: 100px">
                                </a>
                            </td>
                            <td>{{ product.lehenga_desc }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>Rs. {{ item.price }}</td>
                            <td>Rs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: black">
                    <td><b><font color="white" >Total</font></b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b><font color="white" >Rs. {{ cart.get_total_price }}</font></b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "dresses:list" %}" class="btn btn-default" style="color: white; background-color: black">Continue Shopping</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary" style="color: white; background-color: black">Proceed to Pay</a>
        </p>
        </div>
    </div>
{% endblock %}