website/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

website/dresses/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'dresses'

urlpatterns = [
    # /dresses/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/dresses/register
    url(r'^register/$',views.UserFormView.as_view(), name='register'),

    # /dresses/4242/
    url('^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail2'),

    #/dresses/lehengas/add/
    url(r'lehengas/add/$',views.LehengasCreate.as_view(), name='lehenga-add'),

    #dresses/lehengas/2/
    url(r'lehengas/(?P<pk>[0-9]+)/$',views.LehengasUpdate.as_view(), name='lehenga-update'),

    #dresses/lehengas/2/delete
    url(r'lehengas/(?P<pk>[0-9]+)/delete/$',views.LehengasDelete.as_view(), name='lehenga-delete'),

    url(r'login/$', views.login , name='login'),

    url(r'logout/$', views.logout , name='logout'),

    url(r'auth/$', views.auth_view , name='authentiate'),

    url(r'description/$', views.DescView.as_view(), name='description'),

    path('search/',views.search_list,name='search'),

    url(r'^list/$', views.product_list ,name='list')



]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('dresses/', include('dresses.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/dresses/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Lehengas(models.Model):
   # lehenga_price = models.IntegerField()
    lehenga_desc = models.CharField(max_length=500)
    lehenga_size = models.CharField(max_length=10)
    lehenga_pic = models.CharField(max_length=10000)
    lehenga_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=10)


    def get_absolute_url(self):
        return reverse('dresses:detail2', kwargs={'pk':self.pk})

    def __str__(self):
        return  self.lehenga_desc + ' - ' + self.lehenga_size

class weddingLehenga(models.Model):
    lehenga = models.ForeignKey(Lehengas, on_delete=models.CASCADE)
    wedL_colour = models.CharField(max_length= 50)

    def __str__(self):
        return self.wedL_colour

website/dresses/forms.py
from  django.contrib.auth.models import User
from  django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'email', 'password']

website/dresses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import Http404
from .models import Lehengas
# from django.template import loader
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.contrib.auth import authenticate
from .forms import UserForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core import *
from django.template.context_processors import csrf
from cart.cart import Cart
from cart.forms import CartAddProductForm
from tkinter import messagebox



# Create your views here.

def product_list(request):
    lehengas = Lehengas.objects.all()
    context = {
        'obj':lehengas
    }
    return render(request, 'dresses/list.html' , context)


def product_detail(request, id,):
    product = get_object_or_404(Lehengas, id=id, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'dresses/detail2.html', context)

class IndexView(generic.ListView):
    template_name = 'dresses/index.html'

    def get_queryset(self):
        return Lehengas.objects.all()


class DetailView(generic.DetailView):
    model = Lehengas
    template_name = 'dresses/detail2.html'


class LehengasCreate(CreateView):
    model = Lehengas
    fields = ['lehenga_desc', 'lehenga_size', 'lehenga_pic','lehenga_price','available','stock']

class LehengasUpdate(UpdateView):
    model = Lehengas
    fields = ['lehenga_desc', 'lehenga_size', 'lehenga_pic','lehenga_price','available','stock']

class LehengasDelete(DeleteView):
    model = Lehengas
    success_url = reverse_lazy('dresses:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'dresses/registration_form.html'

    #dispaly blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    #procss form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            #change password
            user.set_password(password)
            user.save()

            #returns User obj if all is correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request)
                    return redirect('dresses:index')

        #if all is not correct, return blank form
        return render(request, self.template_name, {'form': form})


def login(request):
    c = {
    }
    c.update(csrf(request))
    return render_to_response('dresses/login.html', c)

def logout(request):
    return redirect('dresses:index')

def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = authenticate(username=username, password=password)
    if user is not None:
        return redirect('dresses:index')
    else:
        msg = 'Please enter correct Username and Password'
        messagebox.showerror("Error", msg)
        return render(request, 'dresses/login.html', {'error': msg})

class DescView(generic.ListView):
    model = Lehengas
    template_name = 'dresses/description.html'

    def get_queryset(self):
        return Lehengas.objects.all()

def search_list(request):
    search_term = Lehengas.objects.all()
    query = request.GET.get("q")
    if query:
        search_term = search_term.filter(lehenga_desc__icontains=query)
    page_req = 'page'
    page = request.GET.get(page_req, 1)
    paginator = Paginator(search_term, 10)
    try:
        lehengas = paginator.page(page)
    except PageNotAnInteger:
        lehengas = paginator.page(1)
    except EmptyPage:
        lehengas = paginator.page(paginator.num_pages)
    context = {
        "object_list": search_term,
        "legenga_size": query
    }
    return render(request, 'dresses/search.html', {'lehengas':lehengas})

website/dresses/templates/dresses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TrendSetter{% endblock %}</title>

    <!-- Loads the path to ur static files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dresses/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- //for bootstrap working -->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<img align="right" src="http://thenewswheel.com/wp-content/uploads/2015/10/Tesla-T-logo.jpg" height="75" width="75"/>
		</div>
		<div class="col-md-6">
            <h3><a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a></h3>
		</div>
	</div>
</div>
</nav>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <!-- 3 lines -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- <a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a> -->
            </div>


            <!-- Items -->
            <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav menu__list">
                        <li class="active menu__item menu__item--current"><a class="menu__link" href="{% url 'dresses:index' %}">Home <span class="sr-only">(current)</span></a></li>
                        <li class=" menu__item"><a class="menu__link" href="{% url 'dresses:description' %}">Discounted Lehengas</a></li>
                        <li class="dropdown menu__item">

                        <li class="dropdown menu__item">
                           <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Women's wear <span class="caret"></span></a>

                          <ul class="dropdown-menu multi-column columns-3">
                                    <div class="agile_inner_drop_nav_info">
                                        <div class=""><!--"col-sm-3 multi-gd-img"-->
                                            <ul class="multi-column-dropdown">

                                            {% if object_list %}
                                            {% for lehenga in object_list %}
                                            <li><a href="{% url 'dresses:detail2' lehenga.id %}">{{ lehenga.lehenga_desc}}</a> </li>
                                            {% endfor %}

                                            {% else %}
                                            <h6>You dont have any lehenga</h6>
                                            {% endif %}

                                            <!--

                                                <li><a href="detail.html">Clothing</a></li>
                                                <li><a href="detail.html">Wallets</a></li>
                                                <li><a href="womens.html">Footwear</a></li>

                                            -->
                                            </ul>
                                        </div>

                                        <!--
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="womens.html">Jewellery</a></li>
                                                <li><a href="womens.html">Sunglasses</a></li>
                                            </ul>
                                        </div>

                                        <div class="col-sm-6 multi-gd-img multi-gd-text ">
                                            <a href="womens.html"><img src="images/top1.jpg" alt=" "/></a>
                                        </div>
                                        <div class="clearfix"></div>
                                        -->
                                    </div>

                                </ul>
                        </li>

                       <!-- <li class=" menu__item"><a class="menu__link" href="contact.html">Contact</a></li>
                        -->

                        <form class="navbar-form navbar-left"  method="get" action="{% url 'dresses:search' %}">
                        <div class="form-group">
                            <input type="text"  name="q" >
                        </div>
                        <button type="submit" >Search</button>
                        </form>
                        <li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com" class="glyphicon glyphicon-envelope"> info@example.com</a></li>

                      </ul>

                      <ul class="nav navbar-nav navbar-right">
                          <!--
                          <li class="">
                              <a href="{% url 'dresses:lehenga-add' %}">
                                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Lehenga
                              </a>
                          </li>
                          -->

                          <li class="">
                              <a href="{% url 'dresses:register' %}">
                                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Register
                              </a>
                          </li>

                          <li>
                            {% if user.username %}
                                <a href="{% url 'dresses:logout' %}">
                                <span class="glyphicon glyphicon-off">Logout </span></a>
                            {% else %}
                                <a href="{% url 'dresses:login' %}">
                                <span class="glyphicon glyphicon-off">Login </span></a>
                            {% endif %}

                          </li>

                          <li class="">
                              <a href="{% url 'cart:cart_detail' %}" ><button class="	glyphicon glyphicon-shopping-cart" aria-hidden="true"></button></a>
                          </li>

                      </ul>
                    </div>
        </div>
    </nav>
    <!-- End of navbar -->
    {% block body %}
    {% endblock %}
</body>
</html>

website/dresses/templates/dresses/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TrendSetter{% endblock %}</title>

    <!-- Loads the path to ur static files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dresses/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- //for bootstrap working -->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>


</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<img align="right" src="http://thenewswheel.com/wp-content/uploads/2015/10/Tesla-T-logo.jpg" height="75" width="75"/>
		</div>
		<div class="col-md-6">
            <h3><a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a></h3>
		</div>
	</div>
</div>
</nav>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <!-- 3 lines -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- <a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a> -->
            </div>


            <!-- Items -->
            <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav menu__list">
                        <li class="active menu__item menu__item--current"><a class="menu__link" href="{% url 'dresses:index' %}">Home <span class="sr-only">(current)</span></a></li>
                        <li class=" menu__item"><a class="menu__link" href="{% url 'dresses:description' %}">Discounted Lehengas</a></li>
                        <li class="dropdown menu__item">

                        <li class="dropdown menu__item">
                           <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Women's wear <span class="caret"></span></a>

                          <ul class="dropdown-menu multi-column columns-3">
                                    <div class="agile_inner_drop_nav_info">
                                        <div class=""><!--"col-sm-3 multi-gd-img"-->
                                            <ul class="multi-column-dropdown">

                                            {% if object_list %}
                                            {% for lehenga in object_list %}
                                            <li><a href="{% url 'dresses:detail2' lehenga.id %}">{{ lehenga.lehenga_desc}}</a> </li>
                                            {% endfor %}

                                            {% else %}
                                            <h6>You dont have any lehenga</h6>
                                            {% endif %}

                                            <!--

                                                <li><a href="detail.html">Clothing</a></li>
                                                <li><a href="detail.html">Wallets</a></li>
                                                <li><a href="womens.html">Footwear</a></li>

                                            -->
                                            </ul>
                                        </div>

                                        <!--
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="womens.html">Jewellery</a></li>
                                                <li><a href="womens.html">Sunglasses</a></li>
                                            </ul>
                                        </div>

                                        <div class="col-sm-6 multi-gd-img multi-gd-text ">
                                            <a href="womens.html"><img src="images/top1.jpg" alt=" "/></a>
                                        </div>
                                        <div class="clearfix"></div>
                                        -->
                                    </div>

                                </ul>
                        </li>

                       <!-- <li class=" menu__item"><a class="menu__link" href="contact.html">Contact</a></li>
                        -->

                        <form class="navbar-form navbar-left"  method="get" action="{% url 'dresses:search' %}">
                        <div class="form-group">
                            <input type="text"  name="q" >
                        </div>
                        <button type="submit" >Search</button>
                        </form>
                        <li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com" class="glyphicon glyphicon-envelope"> info@example.com</a></li>

                      </ul>

                      <ul class="nav navbar-nav navbar-right">
                          <!--
                          <li class="">
                              <a href="{% url 'dresses:lehenga-add' %}">
                                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Lehenga
                              </a>
                          </li>
                          -->

                          <li class="">
                              <a href="{% url 'dresses:register' %}">
                                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Register
                              </a>
                          </li>

                          <li> <a href="{% url 'dresses:logout' %}">

                              <span class="glyphicon glyphicon-off">Logout </span>
                          </a></li>

                          <li class="">
                              <a href="{% url 'cart:cart_detail' %}" ><button class="	glyphicon glyphicon-shopping-cart" aria-hidden="true"></button></a>

                          </li>

                      </ul>
                    </div>
        </div>
    </nav>
    <!-- End of navbar -->
    {% block body %}
    {% endblock %}
</body>
</html>

website/dresses/templates/dresses/login.html
<!-- if u want navbar include this :
extends 'dresses/base.html' or doNotUse.html like in index.html -->
<style>
    div.col-md-6 {
        border-style: solid;
        border-width: 5px;
        border-radius: 15px;
    }
    input.user,input.pass {
        border-style: solid;
        border-width:thin;
        border-radius: 5px;
    }
</style>
{% block body %}
    {% include 'dresses/doNotUse.html' %}
<br><br><br>
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
		</div>
		<div class="col-md-8">
            <h4 align="center">To avail discount please login</h4>
			<div class="row">

				<div class="col-md-3">
				</div>
				<div class="col-md-6">

                    <div class="container-fluid" align="center">
                      <h2>Login</h2>
                        <br><br>
                      <form method="post" class="form-signup" action="{% url 'dresses:authentiate' %}">
                        {% csrf_token %}

                          <input type="text" name="username" value="" class="user"><br><br>
                          <input type="password" name="password" value="" class="pass"><br><br>

                          <input type="checkbox">Remember Me<br><br>
                          <button type="submit"><b>Login</b></button><br>
                      </form>
                        <form action="{% url 'dresses:register' %}">
                          <button type="submit"><b>Register</b></button>
                    </form>


                        </div>

				</div>
				<div class="col-md-3">
				</div>
			</div>
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div>


{% endblock %}

website/dresses/templates/dresses/loginBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TrendSetter{% endblock %}</title>

    <!-- Loads the path to ur static files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dresses/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- //for bootstrap working -->
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>


</head>
<nav>
<nav class="navbar navbar-default">
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			<img align="right" src="http://thenewswheel.com/wp-content/uploads/2015/10/Tesla-T-logo.jpg" height="75" width="75"/>
		</div>
		<div class="col-md-6">
            <h3><a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a></h3>
		</div>
	</div>
</div>


    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <!-- 3 lines -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- <a class="navbar-brand" href="{% url 'dresses:index' %}">TrendSetter</a> -->
            </div>


            <!-- Items -->
            <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav menu__list">
                        <li class="active menu__item menu__item--current"><a class="menu__link" href="{% url 'dresses:index' %}">Home <span class="sr-only">(current)</span></a></li>
                        <li class=" menu__item"><a class="menu__link" href="about.html">About</a></li>
                        <li class="dropdown menu__item">

                        <li class="dropdown menu__item">
                           <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Women's wear <span class="caret"></span></a>

                          <ul class="dropdown-menu multi-column columns-3">
                                    <div class="agile_inner_drop_nav_info">
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                            {% if object_list %}
                                            {% for lehenga in object_list %}
                                            <li><a href="{% url 'dresses:detail2' lehenga.id %}">{{ lehenga.lehenga_desc}}</a> </li>
                                            {% endfor %}

                                            {% else %}
                                            <h3>You dont have any lehenga</h3>
                                            {% endif %}
                                            <!--

                                                <li><a href="detail.html">Clothing</a></li>
                                                <li><a href="detail.html">Wallets</a></li>
                                                <li><a href="womens.html">Footwear</a></li>
                                                <li><a href="womens.html">Watches</a></li>
                                                <li><a href="womens.html">Accessories</a></li>
                                                <li><a href="womens.html">Bags</a></li>
                                                <li><a href="womens.html">Caps & Hats</a></li>

                                            -->
                                            </ul>
                                        </div>

                                        <!--
                                        <div class="col-sm-3 multi-gd-img">
                                            <ul class="multi-column-dropdown">
                                                <li><a href="womens.html">Jewellery</a></li>
                                                <li><a href="womens.html">Sunglasses</a></li>
                                            </ul>
                                        </div>

                                        <div class="col-sm-6 multi-gd-img multi-gd-text ">
                                            <a href="womens.html"><img src="images/top1.jpg" alt=" "/></a>
                                        </div>
                                        <div class="clearfix"></div>
                                        -->
                                    </div>

                                </ul>
                        </li>

                        <li class=" menu__item"><a class="menu__link" href="contact.html">Contact</a></li>


                        <form class="navbar-form navbar-left"  method="get" action="{% url 'dresses:search' %}">
                        <div class="form-group">
                            <input type="text"  name="q" >
                        </div>
                        <button type="submit" >Search</button>
                        </form>
                        <li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com" class="glyphicon glyphicon-envelope"> info@example.com</a></li>

                      </ul>

                      <ul class="nav navbar-nav navbar-right">
                          <!--
                          <li class="">
                              <a href="{% url 'dresses:lehenga-add' %}">
                                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Lehenga
                              </a>
                          </li>
                          -->

                          <li class="">
                              <a href="{% url 'dresses:register' %}">
                                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Register
                              </a>
                          </li>

                          <li> <a href="{% url 'dresses:login' %}">
                              <span class="glyphicon glyphicon-off">Login </span>
                          </a></li>

                          <li class="">

                               <button class="	glyphicon glyphicon-shopping-cart" aria-hidden="true" onclick="myFunction()"></button>&nbsp
                                 <script>
                                function myFunction() {
                                    alert("Cart is Empty");
                                }
                                </script>

                          </li>

                      </ul>
                    </div>
        </div>
    </nav>
</nav>
    <!-- End of navbar -->
    {% block body %}
    {% endblock %}
</body>
</html>